scoutmaker/scoutmaker-backend-v2-nest

package.json, src/main.ts, yarn.lock
=> feat: init swagger

src/countries/countries.controller.ts, src/countries/countries.module.ts, src/countries/countries.service.ts, src/countries/dto/find-all.dto.ts, src/guards/auth.guard.ts, src/main.ts, src/middleware/prepare-query.middleware.ts, src/pagination/pagination-options.decorator.ts, src/pagination/pagination-options.dto.ts, src/types/express.d.ts, src/utils/api-response/api-response.dto.ts, src/utils/constants.ts, src/utils/helpers.ts
=> feat: implement basic pagination system

package.json, prisma/schema.prisma, prisma/seed.ts
=> feat: add sample data and seed script

prisma/schema.prisma
=> feat: add scoutmakerv1Id to some models

src/modules/insider-notes/dto/find-all-insider-notes.dto.ts, src/modules/insider-notes/insider-notes.service.ts, src/modules/notes/dto/find-all-notes.dto.ts, src/modules/notes/notes.service.ts, src/modules/orders/dto/find-all-orders.dto.ts, src/modules/orders/orders.service.ts, src/modules/players/dto/find-all-players.dto.ts, src/modules/players/players.service.ts, src/modules/reports/dto/find-all-reports.dto.ts, src/modules/reports/reports.service.ts, src/modules/teams/dto/find-all-teams.dto.ts, src/modules/teams/teams.service.ts, src/utils/helpers.ts
Add multi filters for modules:
- teams
- players
- notes
- insider-notes
- reports
- orders
=> Feat/scout 6.2 multi filters

src/modules/matches/dto/find-all-matches.dto.ts, src/modules/matches/dto/matches-pagination-options.dto.ts, src/modules/matches/matches.service.ts, src/modules/reports/dto/find-all-reports.dto.ts, src/modules/reports/reports.service.ts
- add sorting & filtering by `videoUrl` for matches module
- add filtering by `videoUrl` for reports module
=> Feat/scout 4.3 video filter

src/modules/users/dto/user.dto.ts, src/modules/users/users.service.ts
=> feat: add _count on user dto

package.json, src/app.module.ts, src/modules/mail/sendgrid.module.ts, src/modules/mail/sendgrid.service.ts, src/modules/prisma/prisma.module.ts, yarn.lock
- configure Sendgrid,
- create email service
=> feat: create email service, configure sendgrid

src/main.ts
=> feat: enable cors

src/common/guards/auth.guard.ts, src/modules/auth/auth.controller.ts
=> feat: take the token off of the req header instead of a cookie

src/i18n/en/competition-participations.json, src/i18n/pl/competition-participations.json, src/modules/competition-participations/competition-participations.controller.ts, src/modules/competition-participations/competition-participations.module.ts, src/modules/competition-participations/competition-participations.service.ts, src/modules/competition-participations/dto/competition-participations-pagination-options.dto.ts, src/modules/competition-participations/dto/find-all-competition-participations.dto.ts
Create find all competition participations endpoint with sorting, filtering & pagination
=> feat: create find all competition participations endpoint

src/modules/player-positions/player-positions.controller.ts, src/modules/player-positions/player-positions.service.ts
=> feat: rename player positions list endpoint

src/i18n/en/team-affiliations.json, src/i18n/pl/team-affiliations.json, src/modules/team-affiliations/dto/find-all-team-affiliations.dto.ts, src/modules/team-affiliations/dto/team-affiliation.dto.ts, src/modules/team-affiliations/dto/team-affiliations-pagination-options.dto.ts, src/modules/team-affiliations/team-affiliations.controller.ts, src/modules/team-affiliations/team-affiliations.module.ts, src/modules/team-affiliations/team-affiliations.service.ts
=> feat: create find all team affiliations endpoint

src/modules/user-football-roles/user-football-roles.controller.ts, src/modules/user-football-roles/user-football-roles.service.ts
Rename list endpoint in `User Football Roles` module
=> fix: rename user-football-roles module list endpoint

.github/CODEOWNERS
=> chore: add cocdeowners file

src/modules/seasons/seasons.controller.ts, src/modules/seasons/seasons.service.ts
=> fix: rename seasons list endpoint

src/modules/competitions/dto/find-all-competitions.dto.ts
[SCOUT-105](https://playmakerpro.atlassian.net/browse/SCOUT-105)
- transform level query param type to number
=> [SCOUT-105] fix level query param in competitions module

src/modules/notes/dto/note.dto.ts, src/modules/notes/notes.service.ts
Add note meta data to `GET /` endpoint response
=> fix: adjust notes response

src/i18n/en/report-background-images.json, src/i18n/pl/report-background-images.json, src/modules/report-background-images/dto/find-all-report-background-images.dto.ts, src/modules/report-background-images/dto/report-background-images-pagination-options.dto.ts, src/modules/report-background-images/report-background-images.controller.ts, src/modules/report-background-images/report-background-images.module.ts, src/modules/report-background-images/report-background-images.service.ts
[SCOUT-103](https://playmakerpro.atlassian.net/browse/SCOUT-103)
=> [SCOUT-103] add GET / endpoint for report-background-images module

src/i18n/en/report-templates.json, src/i18n/pl/report-templates.json, src/modules/report-templates/dto/find-all-report-templates.dto.ts, src/modules/report-templates/dto/report-templates-pagination-options.dto.ts, src/modules/report-templates/report-templates.controller.ts, src/modules/report-templates/report-templates.module.ts, src/modules/report-templates/report-templates.service.ts
[SCOUT-100](https://playmakerpro.atlassian.net/browse/SCOUT-100)
=> [SCOUT-100] create GET / endpoint for report templates module

src/i18n/en/seasons.json, src/i18n/pl/seasons.json, src/modules/seasons/dto/find-all-seasons.dto.ts, src/modules/seasons/dto/seasons-pagination-options.dto.ts, src/modules/seasons/seasons.controller.ts, src/modules/seasons/seasons.module.ts, src/modules/seasons/seasons.service.ts
[SCOUT-90](https://playmakerpro.atlassian.net/browse/SCOUT-90)
=> [SCOUT-90] cretae GET / endpoint for seasons module

src/i18n/en/users.json, src/i18n/pl/users.json, src/modules/users/dto/find-all-users.dto.ts, src/modules/users/dto/users-pagination-options.dto.ts, src/modules/users/users.controller.ts, src/modules/users/users.module.ts, src/modules/users/users.service.ts
[SCOUT-89](https://playmakerpro.atlassian.net/browse/SCOUT-89)
=> [SCOUT-89] add GET / endpoint for users module

src/i18n/en/competition-age-categories.json, src/i18n/pl/competition-age-categories.json, src/modules/competition-age-categories/competition-age-categories.controller.ts, src/modules/competition-age-categories/competition-age-categories.module.ts, src/modules/competition-age-categories/competition-age-categories.service.ts, src/modules/competition-age-categories/dto/competition-age-categories-pagination-options.dto.ts, src/modules/competition-age-categories/dto/find-all-competition-age-categories.dto.ts
[SCOUT-92](https://playmakerpro.atlassian.net/browse/SCOUT-92)
=> [SCOUT-92] create GET / endpoint for competition age categories module

src/i18n/en/competition-types.json, src/i18n/pl/competition-types.json, src/modules/competition-types/competition-types.controller.ts, src/modules/competition-types/competition-types.module.ts, src/modules/competition-types/competition-types.service.ts, src/modules/competition-types/dto/competition-types-pagination-options.dto.ts, src/modules/competition-types/dto/find-all-competition-types.dto.ts, src/modules/competition-types/entities/competition-type.entity.ts
[SCOUT-94](https://playmakerpro.atlassian.net/browse/SCOUT-94)
=> [SCOUT-94] create GET / endpoint for competition types module

src/i18n/en/competition-junior-levels.json, src/i18n/pl/competition-junior-levels.json, src/modules/competition-junior-levels/competition-junior-levels.controller.ts, src/modules/competition-junior-levels/competition-junior-levels.module.ts, src/modules/competition-junior-levels/competition-junior-levels.service.ts, src/modules/competition-junior-levels/dto/competition-junior-levels-pagination-options.dto.ts, src/modules/competition-junior-levels/dto/find-all-competition-junior-levels.dto.ts, src/modules/competition-types/competition-types.service.ts
[SCOUT-95](https://playmakerpro.atlassian.net/browse/SCOUT-95)
=> [SCOUT-95] create GET / endpoint for competition junior levels module

src/i18n/en/competition-groups.json, src/i18n/pl/competition-groups.json, src/modules/competition-groups/competition-groups.controller.ts, src/modules/competition-groups/competition-groups.module.ts, src/modules/competition-groups/competition-groups.service.ts, src/modules/competition-groups/dto/competition-groups-pagination-options.dto.ts, src/modules/competition-groups/dto/find-all-competition-groups.dto.ts
[SCOUT-96](https://playmakerpro.atlassian.net/browse/SCOUT-96)
=> [SCOUT-96] create GET / endpoint for competition groups module

src/i18n/en/player-positions.json, src/i18n/pl/player-positions.json, src/modules/player-positions/dto/find-all-player-positions.dto.ts, src/modules/player-positions/dto/player-positions-pagination-options.dto.ts, src/modules/player-positions/player-positions.controller.ts, src/modules/player-positions/player-positions.module.ts, src/modules/player-positions/player-positions.service.ts
[SCOUT-97](https://playmakerpro.atlassian.net/browse/SCOUT-97)
=> [SCOUT-97] create GET / endpoint for player positions module

src/i18n/en/organizations.json, src/i18n/pl/organizations.json, src/modules/competition-junior-levels/dto/organizations-pagination-options.dto.ts, src/modules/organizations/dto/find-all-organizations.dto.ts, src/modules/organizations/organizations.controller.ts, src/modules/organizations/organizations.module.ts, src/modules/organizations/organizations.service.ts
[SCOUT-102](https://playmakerpro.atlassian.net/browse/SCOUT-102)
=> [SCOUT-102] create GET / endpoint for organizations module

src/i18n/en/user-football-roles.json, src/i18n/pl/user-football-roles.json, src/modules/user-football-roles/dto/find-all-user-football-roles.dto.ts, src/modules/user-football-roles/dto/user-football-roles-pagination-options.dto.ts, src/modules/user-football-roles/user-football-roles.controller.ts, src/modules/user-football-roles/user-football-roles.module.ts, src/modules/user-football-roles/user-football-roles.service.ts
[SCOUT-101](https://playmakerpro.atlassian.net/browse/SCOUT-101)
=> [SCOUT-101] create GET / endpoint for user football roles module

src/i18n/en/report-skill-assessment-templates.json, src/i18n/pl/report-skill-assessment-templates.json, src/modules/report-skill-assessment-templates/dto/find-all-report-skill-assessment-templates.dto.ts, src/modules/report-skill-assessment-templates/dto/report-skill-assessment-templates-pagination-options.dto.ts, src/modules/report-skill-assessment-templates/report-skill-assessment-templates.controller.ts, src/modules/report-skill-assessment-templates/report-skill-assessment-templates.module.ts, src/modules/report-skill-assessment-templates/report-skill-assessment-templates.service.ts
[SCOUT-99](https://playmakerpro.atlassian.net/browse/SCOUT-99)
=> [SCOUT-99] create GET / endpoint for report skill assessment templates module

src/modules/orders/orders.service.ts
[SCOUT-108](https://playmakerpro.atlassian.net/browse/SCOUT-108)
Fix filtering by teamIds
=> [SCOUT-108] filter by teamIds

src/modules/orders/orders.service.ts
[SCOUT-109](https://playmakerpro.atlassian.net/browse/SCOUT-109)
=> [SCOUT-109] sort by position

src/modules/insider-notes/dto/insider-note.dto.ts, src/modules/insider-notes/insider-notes.controller.ts, src/modules/insider-notes/insider-notes.service.ts
[SCOUT-110](https://playmakerpro.atlassian.net/browse/SCOUT-110)
=> [SCOUT-110] include meta data in insider notes endpoints response

prisma/migrations/20220911160558_add_transfermarkt_url_to_competitions/migration.sql, prisma/schema.prisma, src/modules/competition-groups/dto/competition-group.dto.ts, src/modules/competition-groups/dto/create-competition-group.dto.ts, src/modules/competitions/dto/competition.dto.ts, src/modules/competitions/dto/create-competition.dto.ts
[SCOUT-115](https://playmakerpro.atlassian.net/browse/SCOUT-115)
=> [SCOUT-115] transfermarkt url for competition

prisma/migrations/20220911161639_region_on_club_optional/migration.sql, prisma/schema.prisma, src/modules/clubs/clubs.service.ts, src/modules/clubs/dto/create-club.dto.ts
[SCOUT-114](https://playmakerpro.atlassian.net/browse/SCOUT-114)
=> [SCOUT-114] region on club optional

src/modules/countries/countries.controller.ts, src/modules/countries/countries.service.ts, src/modules/countries/dto/create-country.dto.ts, src/modules/regions/regions.controller.ts, src/modules/regions/regions.service.ts
[SCOUT-44](https://playmakerpro.atlassian.net/browse/SCOUT-44)
=> [SCOUT-44] add route to create multiple regions from csv input

src/modules/clubs/clubs.controller.ts, src/modules/clubs/clubs.service.ts, src/utils/csv-helpers.ts
[SCOUT-46](https://playmakerpro.atlassian.net/browse/SCOUT-46)
=> [SCOUT-46] add helpers & function to create multiple clubs from csv

src/modules/clubs/clubs.controller.ts, src/modules/clubs/clubs.service.ts, src/modules/user-football-roles/dto/create-user-football-role.dto.ts, src/modules/user-football-roles/user-football-roles.controller.ts, src/modules/user-football-roles/user-football-roles.service.ts, src/modules/users/dto/create-user.dto.ts, src/modules/users/users.controller.ts, src/modules/users/users.service.ts
[SCOUT-176](https://playmakerpro.atlassian.net/browse/SCOUT-176)
=> [SCOUT-176] football roles csv

src/modules/competition-age-categories/competition-age-categories.controller.ts, src/modules/competition-age-categories/competition-age-categories.service.ts, src/modules/competition-groups/competition-groups.controller.ts, src/modules/competition-groups/competition-groups.service.ts, src/modules/competition-groups/dto/competition-group.dto.ts, src/modules/competition-groups/dto/create-competition-group.dto.ts, src/modules/competition-participations/competition-participations.controller.ts, src/modules/competition-participations/competition-participations.service.ts, src/modules/competition-types/competition-types.controller.ts, src/modules/competition-types/competition-types.service.ts, src/modules/competitions/competitions.controller.ts, src/modules/competitions/competitions.service.ts, src/modules/seasons/dto/create-season.dto.ts, src/modules/seasons/seasons.controller.ts, src/modules/seasons/seasons.service.ts, src/modules/users/dto/create-user.dto.ts
[SCOUT-47](https://playmakerpro.atlassian.net/browse/SCOUT-47)
=> [SCOUT-47] competition csv

src/modules/teams/dto/create-team.dto.ts, src/modules/teams/teams.controller.ts, src/modules/teams/teams.service.ts
[SCOUT-48](https://playmakerpro.atlassian.net/browse/SCOUT-48)
=> [SCOUT-48] add method for teams

src/modules/player-positions/player-positions.controller.ts, src/modules/player-positions/player-positions.service.ts
[SCOUT-49](https://playmakerpro.atlassian.net/browse/SCOUT-49)
=> [SCOUT-49] add method for player positions

src/modules/players/dto/create-player.dto.ts, src/modules/players/players.controller.ts, src/modules/players/players.service.ts
[SCOUT-50](https://playmakerpro.atlassian.net/browse/SCOUT-50)
=> [SCOUT-50] add method for players

src/modules/organizations/organizations.controller.ts, src/modules/organizations/organizations.service.ts
[SCOUT-56](https://playmakerpro.atlassian.net/browse/SCOUT-56)
=> [SCOUT-56] add method for organizations

src/modules/insider-notes/insider-notes.controller.ts, src/modules/insider-notes/insider-notes.service.ts, src/modules/matches/matches.controller.ts, src/modules/matches/matches.service.ts, src/modules/notes/notes.controller.ts, src/modules/notes/notes.service.ts
[SCOUT-51](https://playmakerpro.atlassian.net/browse/SCOUT-51)
[SCOUT-52](https://playmakerpro.atlassian.net/browse/SCOUT-52)
[SCOUT-53](https://playmakerpro.atlassian.net/browse/SCOUT-53)
=> [SCOUT-51,52,52] csv

package.json
=> feat: add reset staging script

src/modules/players/dto/create-player.dto.ts, src/modules/players/players.service.ts
=> fix: player csv

src/common/guards/role.guard.ts, src/modules/competitions/competitions.controller.ts, src/modules/seasons/seasons.controller.ts
- add more context to error coming from role guard
- fix endpoint access for `competitions` module
- fix endpoint access for `seasons` module
=> Fix endpoint access

src/modules/organization-subscriptions/dto/organization-subscription.dto.ts, src/modules/user-subscriptions/dto/user-subscription.dto.ts
[SCOUT-120](https://playmakerpro.atlassian.net/browse/SCOUT-120)
Fix `UserSubscriptionDto` & `OrganizationSubscriptionDto`
=> fix: user & organization subscription dtos

src/modules/players/players.service.ts
[SCOUT-182](https://playmakerpro.atlassian.net/browse/SCOUT-182)
Add slug variant to `generateWhereClause` for players service
=> [SCOUT-182] add slug variant to generateWhereClause

src/modules/clubs/clubs.service.ts
[SCOUT-191](https://playmakerpro.atlassian.net/browse/SCOUT-191)
Add case insensitivity to clubs name filter
=> [SCOUT-191] add case insensitivity to clubs name filter

src/modules/clubs/clubs.service.ts, src/modules/teams/teams.service.ts
[SCOUT-192](https://playmakerpro.atlassian.net/browse/SCOUT-192)
Add slug filtering for clubs & teams
=> [SCOUT-192] slug filter

src/common/interceptors/document-access-filters-interceptor.ts, src/modules/insider-notes/guards/read.guard.ts, src/modules/insider-notes/guards/update.guard.ts, src/modules/notes/guards/read.guard.ts, src/modules/notes/guards/update.guard.ts, src/modules/players/guards/read.guard.ts, src/modules/players/guards/update.guard.ts, src/modules/players/interceptors/access-filters.interceptor.ts, src/modules/reports/guards/read.guard.ts, src/modules/reports/guards/update.guard.ts, src/utils/constants.ts
[SCOUT-117](https://playmakerpro.atlassian.net/browse/SCOUT-117)
=> [SCOUT-117] playmaker scout access

src/modules/competition-groups/competition-groups.service.ts
[SCOUT-118](https://playmakerpro.atlassian.net/browse/SCOUT-118)
=> fix: update regions condition

prisma/migrations/20221002132545_remove_report_template_relation/migration.sql, prisma/migrations/20221002135426_all_fields_on_meta_optional/migration.sql, prisma/schema.prisma, src/modules/insider-notes/insider-notes.service.ts, src/modules/notes/notes.service.ts, src/modules/reports/dto/report.dto.ts, src/modules/reports/reports.service.ts
[SCOUT-206](https://playmakerpro.atlassian.net/browse/SCOUT-206)
=> [SCOUT-206] report template relation

src/modules/organizations/organizations.service.ts
[SCOUT-203](https://playmakerpro.atlassian.net/browse/SCOUT-203)
=> [SCOUT-203] remove organization memeber role constraint

src/common/pagination/pagination-options.dto.ts
[SCOUT-204](https://playmakerpro.atlassian.net/browse/SCOUT-204)
=> [SCOUT-204] change minimal paginated data count limit to 1

src/modules/users/dto/user.dto.ts
[SCOUT-202](https://playmakerpro.atlassian.net/browse/SCOUT-202)
=> [SCOUT-202] add email to UserBasicDataDto

src/modules/report-templates/report-templates.controller.ts, src/modules/reports/dto/report.dto.ts
[SCOUT-210](https://playmakerpro.atlassian.net/browse/SCOUT-210)
=> [SCOUT-210] types

src/modules/team-affiliations/dto/create-team-affiliation.dto.ts, src/modules/team-affiliations/team-affiliations.controller.ts, src/modules/team-affiliations/team-affiliations.service.ts
[SCOUT-215](https://playmakerpro.atlassian.net/browse/SCOUT-215)
=> [SCOUT-215] add create many method

src/modules/report-skill-assessment-categories/report-skill-assessment-categories.controller.ts, src/modules/report-skill-assessment-categories/report-skill-assessment-categories.service.ts, src/modules/report-skill-assessment-templates/dto/create-report-skill-assessment-template.dto.ts, src/modules/report-skill-assessment-templates/report-skill-assessment-templates.controller.ts, src/modules/report-skill-assessment-templates/report-skill-assessment-templates.service.ts, src/modules/report-templates/dto/create-report-template.dto.ts, src/modules/report-templates/report-templates.controller.ts, src/modules/report-templates/report-templates.service.ts, src/modules/reports/dto/create-report.dto.ts, src/modules/reports/reports.controller.ts, src/modules/reports/reports.service.ts, src/modules/team-affiliations/team-affiliations.service.ts
[SCOUT-54](https://playmakerpro.atlassian.net/browse/SCOUT-54)
=> [SCOUT-54] report related seed from csv methods

src/modules/organizations/organizations.service.ts
=> fix: stringify memberIds array

src/modules/reports/dto/create-report.dto.ts
[SCOUT-245](https://playmakerpro.atlassian.net/browse/SCOUT-245?atlOrigin=eyJpIjoiNWM0MDYwZGYzYmQzNDUyNmE0MTc4MjYxNjY5ODUyYzUiLCJwIjoiaiJ9)
- fixed editing report when some skills don't have description
=> fix: skill assessment when editing

src/i18n/en/reports.json, src/i18n/pl/reports.json, src/modules/reports/reports.controller.ts, src/modules/reports/reports.service.ts
[SCOUT-226](https://playmakerpro.atlassian.net/browse/SCOUT-226?atlOrigin=eyJpIjoiMjUxYmE2ODAxOWM1NGJmMGFjZmRjMTI0ZTA2OWJmYmIiLCJwIjoiaiJ9)
- added list endpoint to reports
=> feat: add reports list endpoint

src/modules/players/guards/delete.guard.ts, src/modules/players/guards/read.guard.ts, src/modules/players/guards/update.guard.ts
[SCOUT-236](https://playmakerpro.atlassian.net/browse/SCOUT-236?atlOrigin=eyJpIjoiOWI3YWY3ZTYzZDUxNDVjM2FhZmExY2ZmZDA3NDI2MGIiLCJwIjoiaiJ9)
- handle searching by slug in players read guard
=> feat: handle slug

src/modules/user-subscriptions/user-subscriptions.service.ts
[SCOUT-290](https://playmakerpro.atlassian.net/browse/SCOUT-290?atlOrigin=eyJpIjoiZGE3MDhjNWRkYmM1NDFjZDlhN2IxNzFhNWM0NDUxZTUiLCJwIjoiaiJ9)
- fix user subscription caching
=> fix: redis caching

package.json
Add seed admin user script for production database
=> feat: add seed admin script for prod

src/modules/players/players.service.ts
- Parse `transfermarktId` to string 
- accept `primaryPositionid` and assign it to `primaryPositionId` (quick fix for typo in migration csv)
=> fix: transfermarkId & primaryPoistionId issues in player upload

src/modules/matches/dto/matches-pagination-options.dto.ts, src/modules/notes/dto/notes-pagination-options.dto.ts, src/modules/notes/notes.service.ts, src/modules/players/dto/players-pagination-options.dto.ts
[SCOUT-326](https://playmakerpro.atlassian.net/browse/SCOUT-326?atlOrigin=eyJpIjoiMDVkMWI2ZDk5ODQyNDhhMDk4MjU1NDc3M2M1NWRmZTQiLCJwIjoiaiJ9)
- add another sorting options
=> add sorting option

src/modules/reports/dto/reports-pagination-options.dto.ts, src/modules/reports/reports.service.ts
[SCOUT-360](https://playmakerpro.atlassian.net/browse/SCOUT-360?atlOrigin=eyJpIjoiYTFlZjRkNGU5NjRkNDY2NGFmYmQ5YTBhYjE0Yjc1NmQiLCJwIjoiaiJ9)
- added match sortBy to reports
=> add match sorting

src/modules/clubs/clubs.service.ts, src/modules/clubs/dto/club.dto.ts
[SCOUT-327](https://playmakerpro.atlassian.net/browse/SCOUT-327?atlOrigin=eyJpIjoiNDgyYTdlMjZlZTM5NDQyNjhhNTE5ZDAzNjliZDZiYTYiLCJwIjoiaiJ9)
- add teams count to clubs as it's needed for a new column
=> add teams count

src/modules/reports/reports.service.ts
[SCOUT-358](https://playmakerpro.atlassian.net/jira/software/projects/SCOUT/boards/3?assignee=62e7f898d49df231b627099d&selectedIssue=SCOUT-358)
- fixed not returning match data in paginated reports
=> add missing match include

prisma/migrations/20221226132933_add_match_transfermarkt_url/migration.sql, prisma/schema.prisma, src/modules/matches/dto/create-match.dto.ts, src/modules/matches/dto/match.dto.ts
[SCOUT-385](https://playmakerpro.atlassian.net/browse/SCOUT-385?atlOrigin=eyJpIjoiNTAzOTMwMDgyNzFiNDAxNWIwZTY4MWY4MTI0MDQ1NTgiLCJwIjoiaiJ9)
- added optional transfermarktUrl to match
=> add transfermarktUrl to match

.github/PULL_REQUEST_TEMPLATE.md
- added scout link to pr template
=> add scout link

src/modules/report-templates/report-templates.controller.ts, src/modules/report-templates/report-templates.service.ts
[SCOUT-397](https://playmakerpro.atlassian.net/browse/SCOUT-397)
- restricted report-templates list endpoint to return only where you're an author or isPublic is true as it's only used in combos
=> restrict list

prisma/migrations/20230106170439_add_scout_profile/migration.sql, prisma/schema.prisma, src/app.module.ts, src/i18n/en/scout-profiles.json, src/i18n/pl/scout-profiles.json, src/modules/auth/auth.service.ts, src/modules/insider-notes/insider-notes.service.ts, src/modules/notes/notes.service.ts, src/modules/reports/reports.service.ts, src/modules/scout-profiles/dto/create-scout-profile.dto.ts, src/modules/scout-profiles/dto/scout-profile.dto.ts, src/modules/scout-profiles/dto/update-scout-profile.dto.ts, src/modules/scout-profiles/scout-profiles.controller.spec.ts, src/modules/scout-profiles/scout-profiles.controller.ts, src/modules/scout-profiles/scout-profiles.module.ts, src/modules/scout-profiles/scout-profiles.service.spec.ts, src/modules/scout-profiles/scout-profiles.service.ts, src/modules/users/dto/user.dto.ts, src/modules/users/users.service.ts
[SCOUT-278](https://playmakerpro.atlassian.net/browse/SCOUT-278)
- create db model & generate migrations for `ScoutProfile` table
- create scout profile entity on user creation
- create scout profiles REST API module
- include scout profile in response for relevant resources (reports, notes & insider notes)
=> [SCOUT-278] scout profile

src/modules/dashboard/dashboard.service.ts
[SCOUT-438](https://playmakerpro.atlassian.net/browse/SCOUT-438)
update returned dashboard data for pmscoutmanager
=> change returned data for pm-scout-manager

src/modules/notes/notes.service.ts
[SCOUT-445](https://playmakerpro.atlassian.net/browse/SCOUT-445)
- fixed updating note position without player
=> fix position without player

src/modules/notes/notes.service.ts, src/modules/reports/reports.service.ts
[SCOUT-456](https://playmakerpro.atlassian.net/browse/SCOUT-456)
- fix positions filters on observations
=> fix positions filters

src/modules/players/players.service.ts
[SCOUT-457](https://playmakerpro.atlassian.net/browse/SCOUT-457)
- include positions from observations in players filters
=> include positions from observations in filters

src/common/guards/role.guard.ts, src/modules/orders/orders.controller.ts
[SCOUT-460](https://playmakerpro.atlassian.net/browse/SCOUT-460)
- add handling socut in organiztion to role guard
- add scout in organization access to orders
=> add scout in organization access

src/modules/team-affiliations/team-affiliations.service.ts
[SCOUT-461](https://playmakerpro.atlassian.net/browse/SCOUT-461)
- fixed not updating endDate to null when editing
=> handle endDate null

src/modules/reports/reports.service.ts
[SCOUT-464](https://playmakerpro.atlassian.net/browse/SCOUT-464)
- fixed creating report when skills have no rating
=> fix when avgRating NaN

prisma/migrations/20230121145421_player_positions_list_order/migration.sql, prisma/schema.prisma, src/modules/player-positions/dto/create-player-position.dto.ts, src/modules/player-positions/dto/player-position.dto.ts, src/modules/player-positions/dto/player-positions-pagination-options.dto.ts, src/modules/player-positions/player-positions.service.ts
[SCOUT-465](https://playmakerpro.atlassian.net/browse/SCOUT-465)
- added list order property to player positions
=> add player postions list order

prisma/migrations/20230121160213_player_instat_url/migration.sql, prisma/schema.prisma, src/modules/players/dto/create-player.dto.ts, src/modules/players/dto/player.dto.ts
[SCOUT-473](https://playmakerpro.atlassian.net/browse/SCOUT-473)
- add inStat url to player
=> player add inStat url

src/modules/landing/landing.service.ts
[SCOUT-449](https://playmakerpro.atlassian.net/browse/SCOUT-449)
- fixed returning notes count in reports count
=> fix twice notes

src/common/guards/auth.guard.ts, src/modules/users/users.module.ts, src/modules/users/users.service.ts
[SCOUT-480](https://playmakerpro.atlassian.net/browse/SCOUT-480)
- now on auth user information is current from database and cached
=> cache user on auth

src/i18n/en/landing.json, src/i18n/pl/landing.json, src/modules/landing/dto/landing.dto.ts, src/modules/landing/landing.controller.ts
[SCOUT-491](https://playmakerpro.atlassian.net/browse/SCOUT-491)
- added endpoint for sending emails from landing page
=> feat: landing email

src/modules/competition-age-categories/competition-age-categories.controller.ts, src/modules/competition-junior-levels/competition-junior-levels.controller.ts, src/modules/competition-types/competition-types.controller.ts, src/modules/competitions/competitions.controller.ts, src/modules/competitions/competitions.module.ts, src/modules/regions/regions.controller.ts, src/modules/regions/regions.module.ts
[SCOUT-497](https://playmakerpro.atlassian.net/browse/SCOUT-497)
[SCOUT-498](https://playmakerpro.atlassian.net/browse/SCOUT-498)
- made region optional in clubs
- made regions/competitions modules public
related backend pr required
=> make modules public

prisma/migrations/20230219213643_player_footed_optional/migration.sql, prisma/schema.prisma, src/modules/players/dto/create-player.dto.ts, src/modules/players/dto/player.dto.ts, src/modules/players/players.service.ts
[SCOUT-510](https://playmakerpro.atlassian.net/browse/SCOUT-510)
- make footed optional in player
- make footed,weight,height optional in player csv
=> make player footed optional

.github/CODEOWNERS, src/modules/notes/dto/find-all-notes.dto.ts, src/modules/notes/notes.service.ts, src/modules/reports/dto/find-all-reports.dto.ts, src/modules/reports/reports.service.ts
[SCOUT-527](https://playmakerpro.atlassian.net/browse/SCOUT-527)
- add seasons filters
=> add seasons filters

prisma/migrations/20230409214714_add_report_template_id_to_report/migration.sql, prisma/migrations/20230412160917_revert_and_add_skills_order/migration.sql, prisma/schema.prisma, src/modules/report-templates/report-templates.service.ts, src/modules/reports/dto/report.dto.ts, src/modules/reports/reports.service.ts
[SCOUT-519](https://playmakerpro.atlassian.net/browse/SCOUT-519)
- add skills order
=> add skills order

src/modules/notes/notes.service.ts
[SCOUT-528](https://playmakerpro.atlassian.net/browse/SCOUT-528)
correct teams filtering
=> correct teams filtering

src/modules/notes/notes.service.ts
[SCOUT-526](https://playmakerpro.atlassian.net/browse/SCOUT-526)
correct competition filtering in notes
=> update competition filters in note

src/modules/players/players.service.ts
[SCOUT-507](https://playmakerpro.atlassian.net/browse/SCOUT-507)
- correct avg rating equation
=> coorect avg rating equation

prisma/migrations/20230414212852_add_created_by_role/migration.sql, prisma/schema.prisma, src/common/interceptors/document-access-filters-interceptor.ts, src/modules/insider-notes/guards/read.guard.ts, src/modules/insider-notes/insider-notes.controller.ts, src/modules/insider-notes/insider-notes.module.ts, src/modules/insider-notes/insider-notes.service.ts, src/modules/notes/guards/read.guard.ts, src/modules/notes/notes.controller.ts, src/modules/notes/notes.module.ts, src/modules/notes/notes.service.ts, src/modules/players/guards/read.guard.ts, src/modules/players/interceptors/access-filters.interceptor.ts, src/modules/players/players.controller.ts, src/modules/players/players.module.ts, src/modules/players/players.service.ts, src/modules/reports/guards/read.guard.ts, src/modules/reports/reports.controller.ts, src/modules/reports/reports.module.ts, src/modules/reports/reports.service.ts
[SCOUT-468](https://playmakerpro.atlassian.net/browse/SCOUT-468)
- add createdByRole
=> add createdByRole

prisma/migrations/20230417213836_add_compact_categories/migration.sql, prisma/migrations/20230417214121_rename_compact_categories/migration.sql, prisma/schema.prisma, src/modules/report-templates/dto/create-report-template.dto.ts, src/modules/report-templates/dto/report-template.dto.ts, src/modules/reports/dto/report.dto.ts, src/modules/reports/reports.service.ts
[SCOUT-521](https://playmakerpro.atlassian.net/browse/SCOUT-521)
add reports compact categories
=> add compact categories

prisma/migrations/20230423185632_add_club_logourl/migration.sql, prisma/migrations/20230423191507_reverse_change_and_add_organization_logo/migration.sql, prisma/schema.prisma, src/modules/auth/auth.controller.ts, src/modules/organizations/dto/create-organization.dto.ts, src/modules/organizations/dto/organization.dto.ts, src/modules/organizations/dto/update-organization.dto.ts, src/modules/organizations/organizations.service.ts, src/modules/users/dto/user.dto.ts, src/modules/users/users.service.ts
[SCOUT-508](https://playmakerpro.atlassian.net/browse/SCOUT-508)
- added organization logo
=> add organization logo

src/modules/dashboard/dashboard.service.ts
[SCOUT-478](https://playmakerpro.atlassian.net/browse/SCOUT-478)
dashboard fixed  to use createdByRole
=> corrected to use createdByRole

prisma/migrations/20230608122833_add_player_grade/migration.sql, prisma/migrations/20230608201006_player_grade_level_sorting_rename/migration.sql, prisma/migrations/20230610182220_player_grade_add_author/migration.sql, prisma/migrations/20230614163034_add_player_latest_grade/migration.sql, prisma/schema.prisma, src/app.module.ts, src/i18n/en/player-grades.json, src/i18n/pl/player-grades.json, src/modules/player-grades/dto/create-player-grade.dto.ts, src/modules/player-grades/dto/find-all-player-grades.dto.ts, src/modules/player-grades/dto/player-grade.dto.ts, src/modules/player-grades/dto/player-grades-pagination-options.dto.ts, src/modules/player-grades/dto/update-player-grade.dto.ts, src/modules/player-grades/player-grades.controller.spec.ts, src/modules/player-grades/player-grades.controller.ts, src/modules/player-grades/player-grades.module.ts, src/modules/player-grades/player-grades.service.spec.ts, src/modules/player-grades/player-grades.service.ts, src/modules/player-grades/types.ts, src/modules/players/dto/find-all-players.dto.ts, src/modules/players/dto/player.dto.ts, src/modules/players/dto/players-pagination-options.dto.ts, src/modules/players/dto/update-player.dto.ts, src/modules/players/players.service.ts
[SCOUT-537](https://playmakerpro.atlassian.net/browse/SCOUT-537)
- implemented player grades
=> implement player grades

prisma/migrations/20230616123234_player_add_recent_average_percentage_ratings/migration.sql, prisma/migrations/20230616232429_player_recent_avg_rating_add_date_fields/migration.sql, prisma/schema.prisma, src/modules/players/dto/find-all-players.dto.ts, src/modules/players/dto/player.dto.ts, src/modules/players/players.service.ts, src/modules/players/types.ts
[SCOUT-533](https://playmakerpro.atlassian.net/browse/SCOUT-533)
=> implement player recent avg rating

src/modules/dashboard/dashboard.module.ts, src/modules/landing/landing.module.ts, src/modules/matches/matches.module.ts, src/modules/matches/matches.service.ts, src/modules/notes/notes.module.ts, src/modules/notes/notes.service.ts, src/modules/reports/reports.module.ts, src/modules/reports/reports.service.ts, src/modules/team-affiliations/dto/find-all-team-affiliations.dto.ts, src/modules/team-affiliations/team-affiliations.service.ts, src/utils/helpers.ts
[SCOUT-539](https://playmakerpro.atlassian.net/browse/SCOUT-539)
=> correct matches observations assign

src/modules/matches/matches.service.ts
[SCOUT-545](https://playmakerpro.atlassian.net/browse/SCOUT-545)
- matches list sort
=> matches list sort

prisma/migrations/20230702123425_player_grade_optional_competition/migration.sql, prisma/schema.prisma, src/modules/matches/matches.service.ts, src/modules/notes/notes.service.ts, src/modules/player-grades/dto/create-player-grade.dto.ts, src/modules/player-grades/player-grades.service.ts, src/modules/reports/reports.service.ts
[SCOUT-](https://playmakerpro.atlassian.net/browse/SCOUT-)
=> player grade auto competition

src/modules/notes/notes.service.ts, src/modules/reports/reports.service.ts, src/modules/team-affiliations/team-affiliations.service.ts
[SCOUT-550](https://playmakerpro.atlassian.net/browse/SCOUT-550)
- fixed teamId in note/report meta
=> fix team id in meta

src/modules/players/dto/player.dto.ts, src/modules/players/players.cron.ts, src/modules/players/players.service.ts, src/modules/reports/reports.service.ts
[SCOUT-533](https://playmakerpro.atlassian.net/browse/SCOUT-533)
=> correct recent avg rating

prisma/migrations/20230823093546_observations_meta_add_notmatched/migration.sql, prisma/schema.prisma, src/modules/dashboard/dashboard.module.ts, src/modules/landing/landing.module.ts, src/modules/matches/matches.module.ts, src/modules/matches/matches.service.ts, src/modules/notes/notes.module.ts, src/modules/notes/notes.service.ts, src/modules/reports/reports.module.ts, src/modules/reports/reports.service.ts, src/modules/team-affiliations/dto/find-all-team-affiliations.dto.ts, src/modules/team-affiliations/team-affiliations.service.ts, src/modules/teams/teams.module.ts
[SCOUT-556](https://playmakerpro.atlassian.net/browse/SCOUT-556)
=> getting team in observations update
